// <auto-generated />
namespace BankOfBIT_ArshdeepSangha.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class StoredProcedure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoredProcedure));
        
        string IMigrationMetadata.Id
        {
            get { return "201709272240366_StoredProcedure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
